version: "3.8"
services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    volumes:
      - ./db_data/data:/var/lib/mysql
      - ./my.conf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
  WordPress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - ./public_html:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  db_data:  # 永続化